project:
  type: website
  output-dir: _site

website:
  favicon: images/favicon.png
  title: ""
  navbar:
    background: "#0d0054"
    foreground: "#ffffff"
    logo: "images/favicon.png"
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "01 - A Layered Grammar of Graphics: ggplot2 methods"
            href: Hands-on_Ex/Hands-on_Ex01/hands-on_Ex01.qmd
          - text: "02 - Beyond ggplot2 Fundamentals"
            href: Hands-on_Ex/Hands-on_Ex02/hands-on_Ex02.qmd
      - text: "In-class Exercise"
        menu:
          - text: "Coming Soon"
            #href: index.qmd
      - text: "Take-home Exercise"
        menu:
          - text: "Coming Soon"
            #href: index.qmd
    right:
      - icon: house-fill
        text: Home
        href: index.qmd
      - icon: person-circle
        text: About Me
        href: about.qmd
  
  announcement: 
    content: "**NEW (21/04)** - [**Hands-on Exercise 2**](https://isss608-vriadi.netlify.app/hands-on_ex/hands-on_ex02/hands-on_ex02) is published!"
    position: below-navbar
    icon: info-circle
    type: info
    dismissable: true

  page-footer:
    background: "#0d0054"
    foreground: "#ffffff"
    left:
      - "Made with Quarto in RStudio"
    center:
      - icon: c-circle
        text: " Vanessa Riadi 2025"
    right:
      - icon: linkedin
        aria-label: Linkedin
        href: https://www.linkedin.com/in/vanessariadi/
        target: _blank
      - icon: github
        aria-label: Github
        href: https://github.com/vriadi
        target: _blank

  sidebar:
    - # background: "#f1f4f5" 
      title: "Hands-On Exercise"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - section: "Hands-On Excercise"
          contents:
            - text: "01 - A Layered Grammar of Graphics"
              href: Hands-on_Ex/Hands-on_Ex01/hands-on_Ex01.qmd
            - text: "02 - Beyond ggplot2 Fundamentals"
              href: Hands-on_Ex/Hands-on_Ex02/hands-on_Ex02.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    logo: images/favicon.png

editor: visual

brand:
  color:
    background: "#ebf5fb"