project:
  type: website

website:
  title: "ISSS608"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "01 - A Layered Grammar of Graphics: ggplot2 methods"
            href: Hands-on_Ex/Hands-on_Ex01/hands-on_Ex01.qmd
    right:
      - text: Home
        href: index.qmd
      - text: About Me
        href: about.qmd

  page-footer:
    center:
      - icon: linkedin
        aria-label: Linkedin
        href: https://www.linkedin.com/in/vanessariadi/
        target: _blank
      - icon: github
        aria-label: Github
        href: https://github.com/vriadi
        target: _blank

  sidebar:
    - id: handson
      title: "Hands-On"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - section: "Hands-On Excercise"
          contents:
            - text: "01 - A Layered Grammar of Graphics"
              href: Hands-on_Ex/Hands-on_Ex01/hands-on_Ex01.qmd
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual