project:
  type: website
  output-dir: _site

website:
  favicon: images/favicon.png
  title: ""
  navbar:
    background: "#50434f"
    foreground: "#ffffff"
    logo: "images/favicon.png"
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "1 - A Layered Grammar of Graphics: ggplot2 methods"
            href: Hands-on_Ex/Hands-on_Ex01/hands-on_Ex01.html
          - text: "2 - Beyond ggplot2 Fundamentals"
            href: Hands-on_Ex/Hands-on_Ex02/hands-on_Ex02.html
          - text: "3.1 - Programming Interactive Data Visualisation with R"
            href: Hands-on_Ex/Hands-on_Ex03_1/hands-on_Ex03_1.html
          - text: "3.2 - Programming Interactive Data Visualisation with R"
            href: Hands-on_Ex/Hands-on_Ex03_2/hands-on_Ex03_2.html

      - text: "In-class Exercise"
        menu:
          - text: "2 - Superstore Sales and Profit Report"
            href: In-class_Ex/In-class_Ex02/In-class_Ex02.html
      - text: "Take-home Exercise"
        menu:
          - text: "Coming Soon"
            #href: index.qmd
    right:
      - icon: house-fill
        text: Home
        href: index.html
      - icon: person-circle
        text: About Me
        href: about.html
  
  announcement: 
    content: "**NEW (21/04)** - [**Hands-on Exercise 2**](https://isss608-vriadi.netlify.app/hands-on_ex/hands-on_ex02/hands-on_ex02) is published!"
    position: below-navbar
    icon: info-circle
    type: info
    dismissable: true

  page-footer:
    background: "#50434f"
    foreground: "#ffffff"
    left:
      - "Made with Quarto in RStudio"
    center:
      - icon: c-circle
        text: " Vanessa Riadi 2025"
    right:
      - icon: linkedin
        aria-label: Linkedin
        href: https://www.linkedin.com/in/vanessariadi/
        target: _blank
      #- icon: github
        #aria-label: Github
        #href: https://github.com/vriadi
        #target: _blank
      - text: "<img src='/images/tableauwhite.png' style='height:19px; vertical-align:top;'>"
        href: https://public.tableau.com/app/profile/vanessa.riadi/vizzes
        target: _blank

  sidebar:
    - # background: "#f1f4f5" 
      title: "Hands-On Exercise"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - section: "Hands-On Excercise"
          contents:
            - text: "1 - A Layered Grammar of Graphics"
              href: Hands-on_Ex/Hands-on_Ex01/hands-on_Ex01.html
            - text: "2 - Beyond ggplot2 Fundamentals"
              href: Hands-on_Ex/Hands-on_Ex02/hands-on_Ex02.html
            - text: "3.1 - Programming Interactive Data Visualisation with R"
              href: Hands-on_Ex/Hands-on_Ex03_1/hands-on_Ex03_1.html
            - text: "3.2 - Programming Interactive Data Visualisation with R"
              href: Hands-on_Ex/Hands-on_Ex03_2/hands-on_Ex03_2.html
    - title: "In-Class Exercise"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - section: "In-Class Excercise"
          contents:
            - text: "2 - Superstore Sales and Profit Report"
              href: In-class_Ex/In-class_Ex02/In-class_Ex02.html

format:
  html:
    theme: cosmo
    css: styles.css
    logo: images/favicon.png

editor: visual

brand:
  color:
    background: "#ebf5fb"