project:
  type: website
  output-dir: _site

website:
  favicon: images/favicon.png
  title: ""
  
  announcement: 
    content: "**NEW (10/05)** - [**Hands-on Exercise 5**](https://isss608-vriadi.netlify.app/hands-on_ex/hands-on_ex05/hands-on_ex05) is published!"
    position: below-navbar
    icon: info-circle
    type: info
    dismissable: true
    
  navbar:
    background: "#50434f"
    foreground: "#ffffff"
    logo: "images/favicon.png"
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "1 - A Layered Grammar of Graphics: ggplot2 methods"
            href: Hands-on_Ex/Hands-on_Ex01/hands-on_Ex01.html
          - text: "2 - Beyond ggplot2 Fundamentals"
            href: Hands-on_Ex/Hands-on_Ex02/hands-on_Ex02.html
          - text: "3.1 - Programming Interactive Data Visualisation with R"
            href: Hands-on_Ex/Hands-on_Ex03_1/hands-on_Ex03_1.html
          - text: "3.2 - Programming Interactive Data Visualisation with R"
            href: Hands-on_Ex/Hands-on_Ex03_2/hands-on_Ex03_2.html
          - text: "4.1 - Visualising Distribution"
            href: Hands-on_Ex/Hands-on_Ex04_1/hands-on_Ex04_1.html
          - text: "4.2 - Visual Statistical Analysis"
            href: Hands-on_Ex/Hands-on_Ex04_2/hands-on_Ex04_2.html
          - text: "4.3 - Visualising Uncertainty"
            href: Hands-on_Ex/Hands-on_Ex04_3/hands-on_Ex04_3.html
          - text: "4.4 - Funnel Plots for Fair Comparisons"
            href: Hands-on_Ex/Hands-on_Ex04_4/hands-on_Ex04_4.html
          - text: "5 - Modelling, Visualising and Analysing Network Data with R"
            href: Hands-on_Ex/Hands-on_Ex05/hands-on_Ex05.html
          - text: "6 - Visualising and Analysing Time-oriented Data"
            href: Hands-on_Ex/Hands-on_Ex06/hands-on_Ex06.html
          #- text: "9.1 - Creating Ternary Plot with R"
          #  href: Hands-on_Ex/Hands-on_Ex09_1/hands-on_Ex09_1.html
          #- text: "9.2 - Visual Correlation Analysis"
          #  href: Hands-on_Ex/Hands-on_Ex09_2/hands-on_Ex09_2.html
          #- text: "9.3 - Visual Multivariate Analysis with Heatmap"
          #  href: Hands-on_Ex/Hands-on_Ex09_3/hands-on_Ex09_3.html
          #- text: "9.4 - Visual Multivariate Analysis with Parallel Coordinates Plot"
          #  href: Hands-on_Ex/Hands-on_Ex09_4/hands-on_Ex09_4.html
          #- text: "9.5 - Treemap Visualisation with R"
          #  href: Hands-on_Ex/Hands-on_Ex09_5/hands-on_Ex09_5.html

      - text: "In-class Exercise"
        menu:
          - text: "Session 2 - Superstore Sales and Profit Report"
            href: In-class_Ex/In-class_Ex02/In-class_Ex02.html
          - text: "Session 3 - Superstore Sales vs Profit by States Quadrant"
            href: In-class_Ex/In-class_Ex03/In-class_Ex03.html
          - text: "Session 5 - Preparation for VAST 2025 Mini Challenge 1"
            href: In-class_Ex/In-class_Ex05/In-class_Ex05.html
      - text: "Take-home Exercise"
        menu:
          - text: "1.1 - Demographic structures and distribution of Singapore in 2024"
            href: Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html
          - text: "1.2 - Take Home Exercise 1 Part 2"
            href: Take-home_Ex/Take-home_Ex01/Take-home_Ex01_phase2.html
    right:
      - icon: house-fill
        text: Home
        href: index.html
      - icon: person-circle
        text: About Me
        href: about.html
    
  sidebar:
    - # background: "#f1f4f5" 
      title: "Hands-On Exercise"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - section: "Hands-On Exercise 1"
          contents:
            - text: "1 - A Layered Grammar of Graphics"
              href: Hands-on_Ex/Hands-on_Ex01/hands-on_Ex01.html
        - section: "Hands-On Exercise 2"
          contents:
            - text: "2 - Beyond ggplot2 Fundamentals"
              href: Hands-on_Ex/Hands-on_Ex02/hands-on_Ex02.html
        - section: "Hands-On Exercise 3"
          contents:
            - text: "3.1 - Programming Interactive Data Visualisation with R"
              href: Hands-on_Ex/Hands-on_Ex03_1/hands-on_Ex03_1.html
            - text: "3.2 - Programming Interactive Data Visualisation with R"
              href: Hands-on_Ex/Hands-on_Ex03_2/hands-on_Ex03_2.html
        - section: "Hands-On Exercise 4"
          contents:
            - text: "4.1 - Visualising Distribution"
              href: Hands-on_Ex/Hands-on_Ex04_1/hands-on_Ex04_1.html
            - text: "4.2 - Visual Statistical Analysis"
              href: Hands-on_Ex/Hands-on_Ex04_2/hands-on_Ex04_2.html
            - text: "4.3 - Visualising Uncertainty"
              href: Hands-on_Ex/Hands-on_Ex04_3/hands-on_Ex04_3.html
            - text: "4.4 - Funnel Plots for Fair Comparisons"
              href: Hands-on_Ex/Hands-on_Ex04_4/hands-on_Ex04_4.html
        - section: "Hands-On Exercise 5"
          contents:
            - text: "5 - Modelling, Visualising and Analysing Network Data with R"
              href: Hands-on_Ex/Hands-on_Ex05/hands-on_Ex05.html
        - section: "Hands-On Exercise 6"
          contents:
            - text: "6 - Visualising and Analysing Time-oriented Data"
              href: Hands-on_Ex/Hands-on_Ex06/hands-on_Ex06.html
        #- section: "Hands-On Exercise 5"
        #  contents:
            #- text: "9.1 - Creating Ternary Plot with R"
            #  href: Hands-on_Ex/Hands-on_Ex09_1/hands-on_Ex09_1.html
            #- text: "9.2 - Visual Correlation Analysis"
            #  href: Hands-on_Ex/Hands-on_Ex09_2/hands-on_Ex09_2.html
            #- text: "9.3 - Visual Multivariate Analysis with Heatmap"
            #  href: Hands-on_Ex/Hands-on_Ex09_3/hands-on_Ex09_3.html
            #- text: "9.4 - Visual Multivariate Analysis with Parallel Coordinates Plot"
            #  href: Hands-on_Ex/Hands-on_Ex09_4/hands-on_Ex09_4.html
            #- text: "9.5 - Treemap Visualisation with R"
            #  href: Hands-on_Ex/Hands-on_Ex09_5/hands-on_Ex09_5.html
    - title: "In-Class Exercise"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - section: "In-Class Excercise"
          contents:
            - text: "Session 2 - Superstore Sales and Profit Report"
              href: In-class_Ex/In-class_Ex02/In-class_Ex02.html
            - text: "Session 3 - Superstore Sales vs Profit by States Quadrant"
              href: In-class_Ex/In-class_Ex03/In-class_Ex03.html
            - text: "Session 5 - Preparation for VAST 2025 Mini Challenge 1"
              href: In-class_Ex/In-class_Ex05/In-class_Ex05.html
    - title: "Take-Home Exercise"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - section: "Take-Home Exercise 1"
          contents:
            - text: "1 - Demographic structures and distribution of Singapore in 2024"
              href: Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html
            - text: "1.2 - Take Home Exercise 1 Part 2"
              href: Take-home_Ex/Take-home_Ex01/Take-home_Ex01_phase2.html
        - section: "Take-Home Exercise 2"
          contents:
            - text: "COMING SOON"
              #href: Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html
        - section: "Take-Home Exercise 3"
          contents:
            - text: "COMING SOON"
              #href: Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html
            

  page-footer:
    background: "#50434f"
    foreground: "#ffffff"
    left:
      - "Made with Quarto in RStudio"
    center:
      - icon: c-circle
        text: " Vanessa Riadi 2025"
    right:
      - icon: linkedin
        aria-label: Linkedin
        href: https://www.linkedin.com/in/vanessariadi/
        target: _blank
      #- icon: github
        #aria-label: Github
        #href: https://github.com/vriadi
        #target: _blank
      - text: "<img src='/images/tableauwhite.png' style='height:19px; vertical-align:top;'>"
        href: https://public.tableau.com/app/profile/vanessa.riadi/vizzes
        target: _blank

format:
  html:
    theme: cosmo
    css: styles.css
    logo: images/favicon.png

editor: visual

brand:
  color:
    background: "#ebf5fb"