---
title: "Investment Visualisation"
date: "Jun 28, 2025"
date-modified: "last-modified"
format: 
  dashboard:
    css: styles.css
execute: 
  echo: false
editor: visual
---

```{r}
pacman:: p_load(tidyverse, tidyquant, 
                plotly, glue, timetk, readr)
```

```{r}
SGStock <- read_csv("data/SGStock.csv")
```


```{r}
daily_prices <-SGStock %>%
  select(Symbol) %>%
  tq_get(get ="stock.prices",
         from="2025-01-01",
         to=Sys.Date())

daily_prices <- daily_prices %>%
  left_join(SGStock)
```

# DBS
```{r}
start_date <- min(daily_prices$date)
end_date <- max(daily_prices$date)
```

## Row {height=20%}
```{r}
daily_summary <- daily_prices %>%
  filter(Symbol == "D05.SI" &
           date == end_date)
```

```{r}
#| content: valuebox
#| title: "Opening Price"
#| padding: 3px
list(color = "danger",
     value= daily_summary$open
     )
```

```{r}
#| content: valuebox
#| title: "Closing Price"
list(color = "danger",
     value= daily_summary$close
     )
```

```{r}
#| content: valuebox
#| title: "Daily High"
list(color = "danger",
     value= daily_summary$high
     )
```

```{r}
#| content: valuebox
#| title: "Daily Low"
list(color = "danger",
     value= daily_summary$low
     )
```

## Row
```{r}
df <- daily_prices %>%
  filter(Name =="DBS Group")

# Calculate control limits
mean_close <- mean(df$close, na.rm = TRUE)
sd_close <- sd(df$close, na.rm = TRUE)
ucl <- mean_close + 1 * sd_close
lcl <- mean_close - 1 * sd_close

# Add flag column
df <- df %>%
  mutate(flag = case_when(
    close > ucl ~ "Above UCL",
    close < lcl ~ "Below LCL",
    TRUE ~ "Within Limits"
  ))

# Prepare labels and dynamic title
mean_lbl <- paste0("Mean: ", round(mean_close, 2))
ucl_lbl <- paste0("UCL: ", round(ucl, 2))
lcl_lbl <- paste0("LCL: ", round(lcl, 2))

start_lbl <- format(start_date, "%d %B %Y")
end_lbl <- format(end_date, "%d %B %Y")

dynamic_title <- glue("DBS Stock Prices from {start_lbl} to {end_lbl}")
```

```{r}
p <- ggplot(data = df, aes(x = date, y = close)) +
  geom_line(color = "steelblue") +
  geom_hline(yintercept = mean_close, color = "grey0", linetype = "dashed", linewidth = 0.5, alpha = 0.8) +
  geom_hline(yintercept = ucl,         color = "red",   linetype = "dotted", linewidth = 0.5, alpha = 0.8) +
  geom_hline(yintercept = lcl,         color = "red",   linetype = "dotted", linewidth = 0.5, alpha = 0.8) +
  geom_point(aes(color = flag), size = 1) +
  annotate("text",
           x     = min(df$date),
           y     = ucl + 0.3,
           label = ucl_lbl,
           hjust = 0,
           color = "red",
           size  = 3.5) +
  annotate("text",
           x     = min(df$date),
           y     = lcl + 0.3,
           label = lcl_lbl,
           hjust = 0,
           color = "red",
           size  = 3.5) +
  annotate("text",
           x     = min(df$date),
           y     = mean_close + 0.3,
           label = mean_lbl,
           hjust = 0,
           color = "darkgreen",
           size  = 3.5) +
  scale_color_manual(values = c("Above UCL"      = "red",
                                "Below LCL"      = "red",
                                "Within Limits"  = "steelblue")) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %y") +
  labs(title = dynamic_title,
       y     = "closing Price",
       x     = "") +
  theme_classic()

ggplotly(p)
```

# OCBC
```{r}
start_date <- min(daily_prices$date)
end_date <- max(daily_prices$date)
```

## Row {height=20%}
```{r}
daily_summary <- daily_prices %>%
  filter(Symbol == "O39.SI" &
           date == end_date)
```

```{r}
#| content: valuebox
#| title: "Opening Price"
list(color = "danger",
     value= daily_summary$open
     )
```

```{r}
#| content: valuebox
#| title: "Closing Price"
list(color = "danger",
     value= daily_summary$close
     )
```

```{r}
#| content: valuebox
#| title: "Daily High"
list(color = "danger",
     value= daily_summary$high
     )
```

```{r}
#| content: valuebox
#| title: "Daily Low"
list(color = "danger",
     value= daily_summary$low
     )
```

## Row
```{r}
df <- daily_prices %>%
  filter(Name =="OCBC Bank")

# Calculate control limits
mean_close <- mean(df$close, na.rm = TRUE)
sd_close <- sd(df$close, na.rm = TRUE)
ucl <- mean_close + 1 * sd_close
lcl <- mean_close - 1 * sd_close

# Add flag column
df <- df %>%
  mutate(flag = case_when(
    close > ucl ~ "Above UCL",
    close < lcl ~ "Below LCL",
    TRUE ~ "Within Limits"
  ))

# Prepare labels and dynamic title
mean_lbl <- paste0("Mean: ", round(mean_close, 2))
ucl_lbl <- paste0("UCL: ", round(ucl, 2))
lcl_lbl <- paste0("LCL: ", round(lcl, 2))

start_lbl <- format(start_date, "%d %B %Y")
end_lbl <- format(end_date, "%d %B %Y")

dynamic_title <- glue("OCBC Stock Prices from {start_lbl} to {end_lbl}")
```

```{r}
p <- ggplot(data = df, aes(x = date, y = close)) +
  geom_line(color = "steelblue") +
  geom_hline(yintercept = mean_close, color = "grey0", linetype = "dashed", linewidth = 0.5, alpha = 0.8) +
  geom_hline(yintercept = ucl,         color = "red",   linetype = "dotted", linewidth = 0.5, alpha = 0.8) +
  geom_hline(yintercept = lcl,         color = "red",   linetype = "dotted", linewidth = 0.5, alpha = 0.8) +
  geom_point(aes(color = flag), size = 1) +
  annotate("text",
           x     = min(df$date),
           y     = ucl + 0.3,
           label = ucl_lbl,
           hjust = 0,
           color = "red",
           size  = 3.5) +
  annotate("text",
           x     = min(df$date),
           y     = lcl + 0.3,
           label = lcl_lbl,
           hjust = 0,
           color = "red",
           size  = 3.5) +
  annotate("text",
           x     = min(df$date),
           y     = mean_close + 0.3,
           label = mean_lbl,
           hjust = 0,
           color = "darkgreen",
           size  = 3.5) +
  scale_color_manual(values = c("Above UCL"      = "red",
                                "Below LCL"      = "red",
                                "Within Limits"  = "steelblue")) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %y") +
  labs(title = dynamic_title,
       y     = "closing Price",
       x     = "") +
  theme_classic()

ggplotly(p)
```



# UOB
```{r}
start_date <- min(daily_prices$date)
end_date <- max(daily_prices$date)
```

## Row {height=20%}
```{r}
daily_summary <- daily_prices %>%
  filter(Symbol == "U11.SI" &
           date == end_date)
```

```{r}
#| content: valuebox
#| title: "Opening Price"
list(color = "danger",
     value= daily_summary$open
     )
```

```{r}
#| content: valuebox
#| title: "Closing Price"
list(color = "danger",
     value= daily_summary$close
     )
```

```{r}
#| content: valuebox
#| title: "Daily High"
list(color = "danger",
     value= daily_summary$high
     )
```

```{r}
#| content: valuebox
#| title: "Daily Low"
list(color = "danger",
     value= daily_summary$low
     )
```

## Row
```{r}
df <- daily_prices %>%
  filter(Name =="UOB")

# Calculate control limits
mean_close <- mean(df$close, na.rm = TRUE)
sd_close <- sd(df$close, na.rm = TRUE)
ucl <- mean_close + 1 * sd_close
lcl <- mean_close - 1 * sd_close

# Add flag column
df <- df %>%
  mutate(flag = case_when(
    close > ucl ~ "Above UCL",
    close < lcl ~ "Below LCL",
    TRUE ~ "Within Limits"
  ))

# Prepare labels and dynamic title
mean_lbl <- paste0("Mean: ", round(mean_close, 2))
ucl_lbl <- paste0("UCL: ", round(ucl, 2))
lcl_lbl <- paste0("LCL: ", round(lcl, 2))

start_lbl <- format(start_date, "%d %B %Y")
end_lbl <- format(end_date, "%d %B %Y")

dynamic_title <- glue("UOB Stock Prices from {start_lbl} to {end_lbl}")
```

```{r}
p <- ggplot(data = df, aes(x = date, y = close)) +
  geom_line(color = "steelblue") +
  geom_hline(yintercept = mean_close, color = "grey0", linetype = "dashed", linewidth = 0.5, alpha = 0.8) +
  geom_hline(yintercept = ucl,         color = "red",   linetype = "dotted", linewidth = 0.5, alpha = 0.8) +
  geom_hline(yintercept = lcl,         color = "red",   linetype = "dotted", linewidth = 0.5, alpha = 0.8) +
  geom_point(aes(color = flag), size = 1) +
  annotate("text",
           x     = min(df$date),
           y     = ucl + 0.3,
           label = ucl_lbl,
           hjust = 0,
           color = "red",
           size  = 3.5) +
  annotate("text",
           x     = min(df$date),
           y     = lcl + 0.3,
           label = lcl_lbl,
           hjust = 0,
           color = "red",
           size  = 3.5) +
  annotate("text",
           x     = min(df$date),
           y     = mean_close + 0.3,
           label = mean_lbl,
           hjust = 0,
           color = "darkgreen",
           size  = 3.5) +
  scale_color_manual(values = c("Above UCL"      = "red",
                                "Below LCL"      = "red",
                                "Within Limits"  = "steelblue")) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %y") +
  labs(title = dynamic_title,
       y     = "closing Price",
       x     = "") +
  theme_classic()

ggplotly(p)
```



# Singtel
```{r}
start_date <- min(daily_prices$date)
end_date <- max(daily_prices$date)
```

## Row {height=20%}
```{r}
daily_summary <- daily_prices %>%
  filter(Symbol == "Z74.SI" &
           date == end_date)
```

```{r}
#| content: valuebox
#| title: "Opening Price"
list(color = "danger",
     value= daily_summary$open
     )
```

```{r}
#| content: valuebox
#| title: "Closing Price"
list(color = "danger",
     value= daily_summary$close
     )
```

```{r}
#| content: valuebox
#| title: "Daily High"
list(color = "danger",
     value= daily_summary$high
     )
```

```{r}
#| content: valuebox
#| title: "Daily Low"
list(color = "danger",
     value= daily_summary$low
     )
```

## Row
```{r}
df <- daily_prices %>%
  filter(Name =="Singtel")

# Calculate control limits
mean_close <- mean(df$close, na.rm = TRUE)
sd_close <- sd(df$close, na.rm = TRUE)
ucl <- mean_close + 1 * sd_close
lcl <- mean_close - 1 * sd_close

# Add flag column
df <- df %>%
  mutate(flag = case_when(
    close > ucl ~ "Above UCL",
    close < lcl ~ "Below LCL",
    TRUE ~ "Within Limits"
  ))

# Prepare labels and dynamic title
mean_lbl <- paste0("Mean: ", round(mean_close, 2))
ucl_lbl <- paste0("UCL: ", round(ucl, 2))
lcl_lbl <- paste0("LCL: ", round(lcl, 2))

start_lbl <- format(start_date, "%d %B %Y")
end_lbl <- format(end_date, "%d %B %Y")

dynamic_title <- glue("Singtel Stock Prices from {start_lbl} to {end_lbl}")
```

```{r}
p <- ggplot(data = df, aes(x = date, y = close)) +
  geom_line(color = "steelblue") +
  geom_hline(yintercept = mean_close, color = "grey0", linetype = "dashed", linewidth = 0.5, alpha = 0.8) +
  geom_hline(yintercept = ucl,         color = "red",   linetype = "dotted", linewidth = 0.5, alpha = 0.8) +
  geom_hline(yintercept = lcl,         color = "red",   linetype = "dotted", linewidth = 0.5, alpha = 0.8) +
  geom_point(aes(color = flag), size = 1) +
  annotate("text",
           x     = min(df$date),
           y     = ucl + 0.3,
           label = ucl_lbl,
           hjust = 0,
           color = "red",
           size  = 3.5) +
  annotate("text",
           x     = min(df$date),
           y     = lcl + 0.3,
           label = lcl_lbl,
           hjust = 0,
           color = "red",
           size  = 3.5) +
  annotate("text",
           x     = min(df$date),
           y     = mean_close + 0.3,
           label = mean_lbl,
           hjust = 0,
           color = "darkgreen",
           size  = 3.5) +
  scale_color_manual(values = c("Above UCL"      = "red",
                                "Below LCL"      = "red",
                                "Within Limits"  = "steelblue")) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %y") +
  labs(title = dynamic_title,
       y     = "closing Price",
       x     = "") +
  theme_classic()

ggplotly(p)
```



# SIA
```{r}
start_date <- min(daily_prices$date)
end_date <- max(daily_prices$date)
```

## Row {height=20%}
```{r}
daily_summary <- daily_prices %>%
  filter(Symbol == "C6L.SI" &
           date == end_date)
```

```{r}
#| content: valuebox
#| title: "Opening Price"
list(color = "danger",
     value= daily_summary$open
     )
```

```{r}
#| content: valuebox
#| title: "Closing Price"
list(color = "danger",
     value= daily_summary$close
     )
```

```{r}
#| content: valuebox
#| title: "Daily High"
list(color = "danger",
     value= daily_summary$high
     )
```

```{r}
#| content: valuebox
#| title: "Daily Low"
list(color = "danger",
     value= daily_summary$low
     )
```

## Row
```{r}
df <- daily_prices %>%
  filter(Name =="Singapore Airlines")

# Calculate control limits
mean_close <- mean(df$close, na.rm = TRUE)
sd_close <- sd(df$close, na.rm = TRUE)
ucl <- mean_close + 1 * sd_close
lcl <- mean_close - 1 * sd_close

# Add flag column
df <- df %>%
  mutate(flag = case_when(
    close > ucl ~ "Above UCL",
    close < lcl ~ "Below LCL",
    TRUE ~ "Within Limits"
  ))

# Prepare labels and dynamic title
mean_lbl <- paste0("Mean: ", round(mean_close, 2))
ucl_lbl <- paste0("UCL: ", round(ucl, 2))
lcl_lbl <- paste0("LCL: ", round(lcl, 2))

start_lbl <- format(start_date, "%d %B %Y")
end_lbl <- format(end_date, "%d %B %Y")

dynamic_title <- glue("Singapore Airlines Stock Prices from {start_lbl} to {end_lbl}")
```

```{r}
p <- ggplot(data = df, aes(x = date, y = close)) +
  geom_line(color = "steelblue") +
  geom_hline(yintercept = mean_close, color = "grey0", linetype = "dashed", linewidth = 0.5, alpha = 0.8) +
  geom_hline(yintercept = ucl,         color = "red",   linetype = "dotted", linewidth = 0.5, alpha = 0.8) +
  geom_hline(yintercept = lcl,         color = "red",   linetype = "dotted", linewidth = 0.5, alpha = 0.8) +
  geom_point(aes(color = flag), size = 1) +
  annotate("text",
           x     = min(df$date),
           y     = ucl + 0.3,
           label = ucl_lbl,
           hjust = 0,
           color = "red",
           size  = 3.5) +
  annotate("text",
           x     = min(df$date),
           y     = lcl + 0.3,
           label = lcl_lbl,
           hjust = 0,
           color = "red",
           size  = 3.5) +
  annotate("text",
           x     = min(df$date),
           y     = mean_close + 0.3,
           label = mean_lbl,
           hjust = 0,
           color = "darkgreen",
           size  = 3.5) +
  scale_color_manual(values = c("Above UCL"      = "red",
                                "Below LCL"      = "red",
                                "Within Limits"  = "steelblue")) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %y") +
  labs(title = dynamic_title,
       y     = "closing Price",
       x     = "") +
  theme_classic()

ggplotly(p)
```

# CapitaLand
```{r}
start_date <- min(daily_prices$date)
end_date <- max(daily_prices$date)
```

## Row {height=20%}
```{r}
daily_summary <- daily_prices %>%
  filter(Symbol == "C38U.SI" &
           date == end_date)
```

```{r}
#| content: valuebox
#| title: "Opening Price"
list(color = "danger",
     value= daily_summary$open
     )
```

```{r}
#| content: valuebox
#| title: "Closing Price"
list(color = "danger",
     value= daily_summary$close
     )
```

```{r}
#| content: valuebox
#| title: "Daily High"
list(color = "danger",
     value= daily_summary$high
     )
```

```{r}
#| content: valuebox
#| title: "Daily Low"
list(color = "danger",
     value= daily_summary$low
     )
```

## Row
```{r}
df <- daily_prices %>%
  filter(Name =="CapitaLand Mall Trust")

# Calculate control limits
mean_close <- mean(df$close, na.rm = TRUE)
sd_close <- sd(df$close, na.rm = TRUE)
ucl <- mean_close + 1 * sd_close
lcl <- mean_close - 1 * sd_close

# Add flag column
df <- df %>%
  mutate(flag = case_when(
    close > ucl ~ "Above UCL",
    close < lcl ~ "Below LCL",
    TRUE ~ "Within Limits"
  ))

# Prepare labels and dynamic title
mean_lbl <- paste0("Mean: ", round(mean_close, 2))
ucl_lbl <- paste0("UCL: ", round(ucl, 2))
lcl_lbl <- paste0("LCL: ", round(lcl, 2))

start_lbl <- format(start_date, "%d %B %Y")
end_lbl <- format(end_date, "%d %B %Y")

dynamic_title <- glue("CapitaLand Mall Trust Stock Prices from {start_lbl} to {end_lbl}")
```

```{r}
p <- ggplot(data = df, aes(x = date, y = close)) +
  geom_line(color = "steelblue") +
  geom_hline(yintercept = mean_close, color = "grey0", linetype = "dashed", linewidth = 0.5, alpha = 0.8) +
  geom_hline(yintercept = ucl,         color = "red",   linetype = "dotted", linewidth = 0.5, alpha = 0.8) +
  geom_hline(yintercept = lcl,         color = "red",   linetype = "dotted", linewidth = 0.5, alpha = 0.8) +
  geom_point(aes(color = flag), size = 1) +
  annotate("text",
           x     = min(df$date),
           y     = ucl + 0.3,
           label = ucl_lbl,
           hjust = 0,
           color = "red",
           size  = 3.5) +
  annotate("text",
           x     = min(df$date),
           y     = lcl + 0.3,
           label = lcl_lbl,
           hjust = 0,
           color = "red",
           size  = 3.5) +
  annotate("text",
           x     = min(df$date),
           y     = mean_close + 0.3,
           label = mean_lbl,
           hjust = 0,
           color = "darkgreen",
           size  = 3.5) +
  scale_color_manual(values = c("Above UCL"      = "red",
                                "Below LCL"      = "red",
                                "Within Limits"  = "steelblue")) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b %y") +
  labs(title = dynamic_title,
       y     = "closing Price",
       x     = "") +
  theme_classic()

ggplotly(p)
```