{
  "hash": "e5b1729be4826dd510c56998a855b5c7",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home Exercise 1: Demographic structures and distribution of Singapore in 2024\"\nauthor: \"Vanessa Riadi\"\ndate: \"May 9, 2025\"\ndate-modified: \"last-modified\"\nformat:\n  docx\nexecute: \n  echo: true\n  eval: true\n  warning: false\n  freeze: true\n---\n\n\n\n# [1]{style=\"color:#d496d4; background:none;\"} Overview\n\nA local online media company that publishes daily content on digital platforms is planning to release an article on **demographic structures and distribution of Singapore in 2024**.\n\n# [2]{style=\"color:#d496d4; background:none;\"} Objective\n\nAssuming the role of the graphical editor of the media company, you are tasked to prepare at most three data visualisations for the article.\n\n# [3]{style=\"color:#d496d4; background:none;\"} Analytical Toolkit: RStudio\n\nRStudio and Quarto are used as the primary analytical toolkit for this project. The data is processed using appropriate **tidyverse** family of packages and the data visualisation prepared using **ggplot2** and its extensions.\n\nBefore we get started, it is important for us to ensure that the required R packages have been installed.\n\n::: callout-note\n# Install [**pacman**](https://cran.r-project.org/web/packages/pacman/index.html){target=\"_blank\"} package\n\nIf you have yet to install pacman, install itby typing below in the Console:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(repos = c(CRAN = \"https://cloud.r-project.org\"))\ninstall.packages(\"pacman\")\n```\n:::\n\n\n:::\n\nWe then load the following R packages using the `pacman::p_load()` function:\n\n\\- [**tidyverse**](https://www.tidyverse.org/){target=\"_blank\"}, a family of modern R packages specially designed to support data science, analysis and communication task including creating static statistical graphs.\\\n- [**patchwork**](https://patchwork.data-imaginist.com/){target=\"_blank\"} for combining multiple ggplot2 graphs into one figure.\\\n- [**plotly**](https://plotly.com/r/){target=\"_blank\"}, R library for plotting interactive statistical graphs.\\\n- **ggrepel:** a R package provides geoms for ggplot2 to repel overlapping text labels.\\\n- **ggthemes:** a R package provides some extra themes, geoms, and scales for ggplot.\\\n- **hrbrthemes**: a R package provides typography-centric themes and theme components for ggplot2.\\\n- [**qreport**](https://cran.r-project.org/web/packages/qreport/index.html){target=\"_blank\"}: Provides statistical components, tables, and graphs. - [**ggiraph**](https://davidgohel.github.io/ggiraph/){target=\"_blank\"}: for making ‘ggplot’ graphics interactive.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(tidyverse, patchwork,\n               plotly, ggrepel,\n               ggthemes, hrbrthemes, ggiraph, DT, qreport)\n```\n:::\n\n\n\n# [4]{style=\"color:#d496d4; background:none;\"} Data\n\nSingapore Residents by Planning Area / Subzone, Single Year of Age and Sex, June 2024 dataset shared by [Department of Statistics, Singapore(DOS)](https://www.singstat.gov.sg/find-data/search-by-theme/population/geographic-distribution/latest-data){target=\"_blank\"}\n\n## [4.1]{style=\"color:#d496d4; background:none;\"} Load the Data\n\nFirst we load the data.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndemographic_data <- read_csv(\"data/respopagesexfa2024.csv\")\n```\n:::\n\n\n\n![](images/datapreview.jpg)\n\n## [4.2]{style=\"color:#d496d4; background:none;\"} Check the Data\n\n```{r} # THIS IS NOT RUN BECAUSE DT::datatable() produces HTML output\n#| echo: false\n#DT::datatable(demographic_data , options = list(\n#  columnDefs = list(list(className = 'dt-center', targets = 5)),\n#  pageLength = 5,\n#  lengthMenu = c(5, 10, 15, 20)\n#))\n```\n\nFrom the first glance, we notice that there are '0' Pop in the dataset. For this exercise, we will be focusing on the top-level visualization per Planning Areas and granular details like Population per Subzone and Floor Area aren't necessary. We should exclude those rows with zero population values at the Planning Area level. This will help clean up the data and make the visualizations clearer by removing unnecessary zeros. We will do it in [Chapter 4.3](#dataprep)\n\n::: callout-tip\n# Did you know?\n\nThere are more R packages that can help you to view or describe data. E.g. [Hmisc](https://cran.r-project.org/web/packages/Hmisc/index.html){target=\"_blank\"}, [psych](https://cran.r-project.org/web/packages/psych/index.html){target=\"_blank\"}, [**qreport**](https://cran.r-project.org/web/packages/qreport/index.html){target=\"_blank\"} package. I will be using qreport here\n\nIf you have yet to install qreport, install it by typing below in the Console:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(repos = c(CRAN = \"https://cloud.r-project.org\"))\ninstall.packages(\"qreport\")\n```\n:::\n\n\n:::\n\nHere I am using `qreport`package's [dataOverview](https://search.r-project.org/CRAN/refmans/qreport/html/dataOverview.html){target=\"_blank\"} that I already pre-load earlier.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndataOverview(demographic_data, plot = c(\"none\"),)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ndemographic_data has 75696 observations (75696 complete) and 7 variables (7 complete)\n\n\n|Variable |Type       | Distinct|  Info| Symmetry| NAs|Rarest Value            | Frequency of Rarest Value|Mode        | Frequency of Mode|\n|:--------|:----------|--------:|-----:|--------:|---:|:-----------------------|-------------------------:|:-----------|-----------------:|\n|PA       |Nonnumeric |       55| 0.999|    0.991|   0|Central Water Catchment |                       228|Bukit Merah |              3876|\n|SZ       |Nonnumeric |      332| 1.000|    1.000|   0|Admiralty               |                       228|Admiralty   |               228|\n|AG       |Discrete   |       19| 0.997|    1.000|   0|0_to_4                  |                      3984|0_to_4      |              3984|\n|Sex      |Discrete   |        2| 0.750|    1.000|   0|Females                 |                     37848|Females     |             37848|\n|FA       |Discrete   |        6| 0.972|    1.000|   0|<= 60                   |                     12616|<= 60       |             12616|\n|Pop      |Continuous |      183| 0.831|    6.953|   0|1260                    |                         1|0           |             41742|\n|Time     |Discrete   |        1| 0.000|    1.000|   0|2024                    |                     75696|2024        |             75696|\n```\n\n\n:::\n:::\n\n\n\nLet's also count what's the total Pop\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncntpop <- demographic_data %>%\n  summarise(Pop = sum(Pop, na.rm = TRUE)) \nprint(cntpop$Pop)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4187720\n```\n\n\n:::\n:::\n\n\n\n::: {.nursebox .nurse data-latex=\"nurse\"}\n#### **Observation** {.no-top-padding}\n\n-   The data shows Singapore Residents by Planning Area / Subzone, Single Year of Age and Sex as of June 2024 with total population of 4,187,720.\n\n-   We observe that there are 75,696 rows and 7 columns. No missing values are observed. Refer to the column legend in [Appendix A](#appendixa)\n\n-   There are a total of seven attributes. 5 of them are categorical data type and the other three are in numerical data type.\n\n    -   The categorical attributes are: PA, SZ, AG, Sex, FA.\n    -   The numerical attributes are: Pop, Time.\n\n-   We can also observe how many distinct values for each Variable. This will help us think what to use for our visualization.\n:::\n\n## [4.3]{style=\"color:#d496d4; background:none;\"} Data Preparation {#dataprep}\n\n### [4.3.1]{style=\"color:#d496d4; background:none;\"} Cleaning Data\n\nAs mentioned earlier, we will be focusing on the top-level visualization per Planning Areas and granular details like Population per Subzone and Floor Area aren't necessary. Here we will exclude those rows with zero population values at the Planning Area level by using `filter`.\n\n## Cleaned Data\n\n\n\n::: {.cell}\n\n:::\n\n\n\n## Code\n\nClean using `filter` and display as data table\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndemographic_data_clean <- demographic_data %>%\n  filter(Pop > 0)\n\n#DT::datatable(demographic_data_clean , options = list(\n#  columnDefs = list(list(className = 'dt-center', targets = 5)),\n#  pageLength = 5,\n#  lengthMenu = c(5, 10, 15, 20)))\n```\n:::\n\n\n\n### [4.3.2]{style=\"color:#d496d4; background:none;\"} Age Group recoding\n\nWe will be recoding the Age Group to three groups for clearer visualization: Below 20 years, 20-64 Years, 65 years & Over following [National Statistical Standards Recommendations on Definition and Classification of Age](https://www.singstat.gov.sg/-/media/files/standards_and_classifications/nsa.ashx){target=\"_blank\"} (More details in [Appendix B](#appendixb) ).\n\n## Data\n\n\n\n::: {.cell}\n\n:::\n\n\n\n## Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndemographic_data_recode <- demographic_data_clean %>%\n  mutate(\n    AG_recode = recode(\n      AG,\n      \"0_to_4\" = \"Below 20 Years\",\n      \"5_to_9\" = \"Below 20 Years\",\n      \"10_to_14\" = \"Below 20 Years\",\n      \"15_to_19\" = \"Below 20 Years\",\n      \"20_to_24\" = \"20-64 Years\",\n      \"25_to_29\" = \"20-64 Years\",\n      \"30_to_34\" = \"20-64 Years\",\n      \"35_to_39\" = \"20-64 Years\",\n      \"40_to_44\" = \"20-64 Years\",\n      \"45_to_49\" = \"20-64 Years\",\n      \"50_to_54\" = \"20-64 Years\",\n      \"55_to_59\" = \"20-64 Years\",\n      \"60_to_64\" = \"20-64 Years\",\n      \"65_to_69\" = \"65 Years and Above\",\n      \"70_to_74\" = \"65 Years and Above\",\n      \"75_to_79\" = \"65 Years and Above\",\n      \"80_to_84\" = \"65 Years and Above\",\n      \"85_to_89\" = \"65 Years and Above\",\n      \"90_and_over\" = \"65 Years and Above\"\n    )\n  )\n\n#DT::datatable(demographic_data_recode , options = list(\n#  columnDefs = list(list(className = 'dt-center', targets = 5)),\n#  pageLength = 5,\n#  lengthMenu = c(5, 10, 15, 20)))\n```\n:::\n\n\n\n# [5]{style=\"color:#d496d4; background:none;\"} Data Visualisation, Observation, and Insights\n\n## [5.1]{style=\"color:#d496d4; background:none;\"} Top 10 Planning Areas (PA) Ranked by Size of Resident Population (Pop)\n\n# 🎀 Plot 1\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex01-docx_files/figure-docx/unnamed-chunk-11-1.png)\n:::\n:::\n\n\n\n# Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop10PA <- demographic_data_clean %>%\n  group_by(PA) %>%\n  summarise(Pop = sum(Pop, na.rm = TRUE)) %>%\n  slice_max(order_by = Pop, n = 10)\n\ntop10plot <- ggplot(data = top10PA, \n       aes(y = reorder(PA, Pop/1000), x = Pop/1000)) +  # reorder PA by Pop\n  geom_col(show.legend = FALSE, fill = \"pink4\") +\n  geom_text(aes(label = (Pop/1000)),\n            hjust = -0.2, color = \"black\", size = 3) +\n  ggtitle(\"Top 10 Planning Areas in 2024\\nRanked by Size of Singapore Resident Population\",\n  subtitle = paste(\"Total resident population:\", \n                 format(round(cntpop$Pop / 1000, 2), big.mark = \",\"), \n                 \"thousand\")) +\n  labs(\n    y = NULL,\n    x = \"Resident Population\\nin thousands (‘000)\",\n    caption = \"Source: singstat.gov.sg\"\n  ) +\n  theme_ipsum(base_family = \"Arial\",\n  plot_title_size = 14,\n  subtitle_size = 10,\n  caption_size = 8,\n  plot_title_face = \"bold\",\n  caption_face = \"italic\",\n  grid = \"\",\n  axis_title_face = \"bold\",\n  axis_title_size = 11) +\n  theme(axis.text.x = element_blank(),\n        axis.text.y = element_text(size=11, face=\"bold\"),\n        axis.title.x = element_text(hjust = 0.5)\n        )+\n  scale_x_continuous(expand = expansion(mult = c(0, 0.1)))\n\ntop10plot\n```\n:::\n\n\n\n# Deepdive for more insights\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Total population of the top 10 Planning Area\ncntpoptop10 <- top10PA %>%\n  summarise(Pop = sum(Pop, na.rm = TRUE)) \ncat(cntpoptop10$Pop)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n2358550\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# The percentage of the population of the top 10 most populous Planning Area relative to the total population.\nperc_pop_top10 <- (cntpoptop10 / cntpop) * 100\ncat(perc_pop_top10$Pop)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n56.32062\n```\n\n\n:::\n:::\n\n\n\n::: {.nursebox .nurse data-latex=\"nurse\"}\n#### 🎀 **Insights Plot 1** {.no-top-padding}\n\n-   Slightly over half (56.3%) of the 4,187.72 thousand (\\~4.19 million) residents in Singapore stayed in the top 10 planning areas of residence.\n\n-   There were five planning areas with more than 250,000 residents each, namely Tampines, Bedok, Sengkang, Jurong West, and Woodlands.\n\n-   Tampines was the most populated with 284,720 residents.\n:::\n\n## [5.3]{style=\"color:#d496d4; background:none;\"} Age Group and Sex distribution\n\n# 🎀 Plot 2\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex01-docx_files/figure-docx/unnamed-chunk-15-1.png)\n:::\n:::\n\n\n\n# Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Define age group levels and labels\nAG_levels <- c(\n  \"0_to_4\", \"5_to_9\", \"10_to_14\", \"15_to_19\", \"20_to_24\",\n  \"25_to_29\", \"30_to_34\", \"35_to_39\", \"40_to_44\", \"45_to_49\",\n  \"50_to_54\", \"55_to_59\", \"60_to_64\", \"65_to_69\", \"70_to_74\",\n  \"75_to_79\", \"80_to_84\", \"85_to_89\", \"90_and_over\"\n)\n\nAG_labels <- c(\n  \"0-4\", \"5-9\", \"10-14\", \"15-19\", \"20-24\", \"25-29\", \"30-34\", \"35-39\",\n  \"40-44\", \"45-49\", \"50-54\", \"55-59\", \"60-64\", \"65-69\", \"70-74\", \"75-79\",\n  \"80-84\", \"85-89\", \">90\"\n)\n\nAG_lookup <- setNames(AG_labels, AG_levels)\n\n# Compute population shares by age group\nAGsum2 <- demographic_data_clean %>%\n  group_by(AG) %>%\n  summarise(Pop = sum(Pop, na.rm = TRUE), .groups = \"drop\") %>%\n  mutate(\n    AG = factor(AG, levels = AG_levels),\n    Pop_share = Pop / sum(Pop),\n    cum_share = cumsum(Pop_share),\n    percentile = round(cum_share * 100, 1)\n  ) %>%\n  arrange(AG)\n\n# Median and Q3 age groups\nmedian_AG <- AGsum2 %>% filter(cumsum(Pop) >= sum(Pop) / 2) %>% slice(1) %>% pull(AG)\nq3_AG     <- AGsum2 %>% filter(cumsum(Pop) >= sum(Pop) * 0.75) %>% slice(1) %>% pull(AG)\n\n# Convert median and Q3 to labels\nmedian_label <- AG_lookup[as.character(median_AG)]\nq3_label     <- AG_lookup[as.character(q3_AG)]\n\n# Prepare population pyramid data\npyramid_data <- demographic_data_clean %>%\n  group_by(AG, Sex) %>%\n  summarise(Population = sum(Pop, na.rm = TRUE) / 1000, .groups = \"drop\") %>%\n  mutate(\n    AG = factor(AG, levels = AG_levels, labels = AG_labels, ordered = TRUE),\n    PopPercentage = ifelse(Sex == \"Females\", -Population, Population) / sum(Population) * 100,\n    PopPercentage = round(PopPercentage, 2),\n    Signal = ifelse(Sex == \"Females\", -1, 1)\n  )\n\n\n# Create the population pyramid plot\npyramid_plot <- ggplot(pyramid_data, aes(x = AG, y = PopPercentage, fill = Sex)) +\n  geom_bar(stat = \"identity\") +\n  geom_text(aes(y = PopPercentage + Signal * 0.5, label = abs(PopPercentage)),\n            size = 3, color = \"black\") +\n  coord_flip() +\n  scale_fill_manual(values = c(\"Females\" = \"pink2\", \"Males\" = \"steelblue\"),\n                    guide = guide_legend(override.aes = list(fill = NA))) +\n  scale_y_continuous(labels = abs) +\n  annotate(\"segment\", x = median_label, xend = median_label, y = -4, yend = 3.6,\n           color = \"red4\", linewidth = 0.7, linetype = \"dotted\") +\n  annotate(\"text\", x = median_label, y = 5, label = \"Median\",\n           color = \"red4\", size = 2.8, fontface = \"bold\") +\n  annotate(\"segment\", x = q3_label, xend = q3_label, y = -3.65, yend = 3.65,\n           color = \"red4\", linewidth = 0.7, linetype = \"dotted\") +\n  annotate(\"text\", x = q3_label, y = 5, label = \"Q3\",\n           color = \"red4\", size = 2.8, fontface = \"bold\") +\n  ggtitle(\"Population Pyramid of Singapore Residents\\nby Age and Sex 2024\",\n          subtitle = \"in percentage (%)\") +\n  labs(\n    y = \"Population (%)\",\n    x = \"Age Group\",\n    fill = \"Sex\",\n    caption = \"Source: singstat.gov.sg\"\n  ) +\n  theme_ipsum(base_family = \"Arial\",\n              plot_title_size = 14,\n              subtitle_size = 10,\n              caption_size = 8,\n              plot_title_face = \"bold\",\n              caption_face = \"italic\",\n              grid = \"Y\",\n              axis_title_face = \"bold\",\n              axis_title_size = 11,\n              axis_text_size = 8) +\n  theme(\n    strip.text = element_text(face = \"bold\"),\n    axis.title.x = element_text(hjust = 0.5),\n    axis.title.y = element_text(hjust = 0.5),\n    legend.position = \"top\",\n    legend.title = element_blank(),\n    legend.justification = c(0.45, 0),\n    legend.margin = margin(t = -20, r = 0, b = -10, l = 0, unit = \"pt\")\n  )\n\npyramid_plot\n```\n:::\n\n\n\n# Alternative Plot\n\nAlternatively for more simpler visualisation we can also use this plot, though we can only infer Age Distribution Insights from this plot.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex01-docx_files/figure-docx/unnamed-chunk-17-1.png)\n:::\n:::\n\n\n\n# Deepdive for more insights\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Details of the population pyramid distribution\nprint(pyramid_data, n = 38)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 38 × 5\n   AG    Sex     Population PopPercentage Signal\n   <ord> <chr>        <dbl>         <dbl>  <dbl>\n 1 0-4   Females      83.4          -1.99     -1\n 2 0-4   Males        87.5           2.09      1\n 3 10-14 Females     100.           -2.4      -1\n 4 10-14 Males       104.            2.49      1\n 5 15-19 Females     104.           -2.49     -1\n 6 15-19 Males       107.            2.56      1\n 7 20-24 Females     110.           -2.64     -1\n 8 20-24 Males       115.            2.74      1\n 9 25-29 Females     135.           -3.22     -1\n10 25-29 Males       135.            3.23      1\n11 30-34 Females     166.           -3.95     -1\n12 30-34 Males       156.            3.71      1\n13 35-39 Females     166            -3.96     -1\n14 35-39 Males       149.            3.56      1\n15 40-44 Females     164.           -3.92     -1\n16 40-44 Males       147.            3.5       1\n17 45-49 Females     158.           -3.77     -1\n18 45-49 Males       144.            3.44      1\n19 50-54 Females     158.           -3.78     -1\n20 50-54 Males       149.            3.56      1\n21 55-59 Females     150.           -3.58     -1\n22 55-59 Males       145.            3.46      1\n23 5-9   Females      98.9          -2.36     -1\n24 5-9   Males       104.            2.47      1\n25 60-64 Females     150.           -3.57     -1\n26 60-64 Males       147.            3.52      1\n27 65-69 Females     136.           -3.25     -1\n28 65-69 Males       130.            3.12      1\n29 70-74 Females     107.           -2.57     -1\n30 70-74 Males        99.3           2.37      1\n31 75-79 Females      72.9          -1.74     -1\n32 75-79 Males        61.9           1.48      1\n33 80-84 Females      45.1          -1.08     -1\n34 80-84 Males        32.7           0.78      1\n35 85-89 Females      27.2          -0.65     -1\n36 85-89 Males        16.9           0.4       1\n37 >90   Females      17.4          -0.42     -1\n38 >90   Males         7.73          0.18      1\n```\n\n\n:::\n\n```{.r .cell-code}\n# Details of the AG distribution\nAGsum2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 19 × 5\n   AG             Pop Pop_share cum_share percentile\n   <fct>        <dbl>     <dbl>     <dbl>      <dbl>\n 1 0_to_4      170930   0.0408     0.0408        4.1\n 2 5_to_9      202420   0.0483     0.0892        8.9\n 3 10_to_14    204610   0.0489     0.138        13.8\n 4 15_to_19    211560   0.0505     0.189        18.9\n 5 20_to_24    225020   0.0537     0.242        24.2\n 6 25_to_29    270090   0.0645     0.307        30.7\n 7 30_to_34    321010   0.0767     0.383        38.3\n 8 35_to_39    315180   0.0753     0.459        45.9\n 9 40_to_44    310700   0.0742     0.533        53.3\n10 45_to_49    301820   0.0721     0.605        60.5\n11 50_to_54    307760   0.0735     0.678        67.8\n12 55_to_59    294500   0.0703     0.749        74.9\n13 60_to_64    297020   0.0709     0.820        82  \n14 65_to_69    266580   0.0637     0.883        88.3\n15 70_to_74    206760   0.0494     0.933        93.3\n16 75_to_79    134810   0.0322     0.965        96.5\n17 80_to_84     77750   0.0186     0.983        98.3\n18 85_to_89     44050   0.0105     0.994        99.4\n19 90_and_over  25150   0.00601    1           100  \n```\n\n\n:::\n:::\n\n\n\n::: {.nursebox .nurse data-latex=\"nurse\"}\n#### 🎀 **Insights Plot 2** {.no-top-padding}\n\n-   The median age falls within 40 to 44 age group. About 25% are aged 60 and above, with 18% aged 65 and older, highlighting [aging population trend](https://www.weforum.org/stories/2023/09/life-expectancy-countries-ageing-populations/){target=\"_blank\"}.\n-   Children (0–14) account for only about 13.8% of the population, indicating low birth rates. Slightly more males than females are observed in this group.\n-   The working-age population (15–64 years), as defined by the [Ministry of Manpower](https://stats.mom.gov.sg/Statistics/Pages/labourforce.aspx){target=\"_blank\"}, comprises around 68.2% of the population. This reflects a strong labour force, though future demographic challenges may arise as this group continues to age.\n-   The 25-64 age group shows a near-equal gender balance.\n-   The gender gap widens in the older age cohorts, with majority female in the 80+ age groups. This show that females live longer than males on average, consistent with the life expectancy at birth between the different gendersfrom [2023 report by the Singapore Department of Statistics](https://www.singstat.gov.sg/-/media/files/publications/population/lifetable22-23.ashx){target=\"_blank\"}.\n:::\n\n## [5.3]{style=\"color:#d496d4; background:none;\"} Association Between Age Group Distribution and Planning Area in Singapore\n\n# 🎀 Plot 3\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex01-docx_files/figure-docx/unnamed-chunk-19-1.png)\n:::\n:::\n\n\n\n# Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable_data <- table(demographic_data_recode$AG_recode, demographic_data_recode$PA)\n\nchi_test <- chisq.test(table_data)\n\nresiduals_df <- as.data.frame(as.table(chi_test$residuals))\n\nAG_levels <- c(\"Below 20 Years\", \"20-64 Years\", \"65 Years and Above\")\n\nAG_labels <- c(\"Below 20 Years\", \"20-64 Years\", \"65 Years and Above\")\n\nresiduals_df <- residuals_df %>%\n  mutate(Var1 = factor(Var1, levels = AG_levels, labels = AG_labels, ordered = TRUE))\n\nggplot(residuals_df, aes(Var1, Var2, fill = Freq)) +\n  geom_tile() +\n  geom_text(aes(label = round(Freq, 2)), size = 4) +\n  scale_fill_gradient2(low = \"steelblue\", high = \"red3\", mid = \"white\", midpoint = 0) +\n  labs(x = \"AG\", y = \"PA\", fill = \"Residuals\") +\n  ggtitle(\"Association Between Age Group\\nand Planning Area in Singapore 2024\",\n          subtitle = \"Meassured using Pearson's Chi-squared test\") +\n  labs(caption = \"Source: singstat.gov.sg\")+\n  theme_ipsum(base_family = \"Arial\",\n              plot_title_size = 14,\n              subtitle_size = 10,\n              caption_size = 8,\n              plot_title_face = \"bold\",\n              caption_face = \"italic\",\n              grid = \"Y\",\n              axis_title_face = \"bold\",\n              axis_title_size = 11,\n              axis_text_size = 8) +\n  theme(\n    strip.text = element_text(face = \"bold\"),\n    axis.text.x = element_text(size=10, face=\"bold\", angle = -45, hjust = 0),\n    axis.text.y = element_text(size=10),\n    axis.title.x = element_blank(),\n    axis.title.y = element_blank(),\n    legend.title = element_blank(),\n    legend.justification = c(0.45, 0),\n    legend.margin = margin(t = -20, r = 0, b = -10, l = 0, unit = \"pt\"))+\n  scale_x_discrete(expand = expansion(add = 0.5)) +\n  scale_y_discrete(expand = expansion(add = 0.5)) \n```\n:::\n\n\n\n::: {.nursebox .nurse data-latex=\"nurse\"}\n#### 🎀 **Insights Plot 3** {.no-top-padding}\n\n-   [Central Areas](https://www.hdb.gov.sg/about-us/history/hdb-towns-your-home/central){target=\"_blank\"} like Downtown Core are skewed toward working-age group with strong over-representation of the 20–64 group (+7.46) and lesser children (–4.03) and seniors (–6.69), reflecting its role as a Central Business District. Similar patterns appear in Newton, Museum (Bras Basah, Dhoby Ghaut, Fort Canning), and Singapore River (Boat Quay, Clarke Quay, Robertson Quay).\n\n-   New BTO areas like [Tengah](https://www.hdb.gov.sg/about-us/history/hdb-towns-your-home/tengah){target=\"_blank\"} and [Punggol](https://www.hdb.gov.sg/about-us/history/hdb-towns-your-home/punggol){target=\"_blank\"} show more children and lesser seniors, indicating young families moving into new Towns / Planning Areas.\n\n-   [Mature Towns](https://www.channelnewsasia.com/singapore/mature-estates-hdb-flats-classified-cna-explains-3581846#:~:text=The%20mature%20towns%20and%20estates,Serangoon%2C%20Tampines%20and%20Toa%20Payoh.){target=\"_blank\"} such as Bedok, Ang Mo Kio, and Hougang exhibit neutral residuals, suggesting stable populations with a mix of age groups and long-term residents.\n\n-   Affluent Districts such as [Bukit Timah](https://www.propertyasiadirect.com/sg/places/bukit-timah/#google_vignette){target=\"_blank\"}, we observe more children (+1.98) and 20-65 group (+2.99) with lesser seniors (-5.75). Proximity to \"good schools\" for *kiasu* parents likely attracts young wealthy families with its abundance of private housing. Similar trends observed in Tanglin.\n:::\n\n# [6]{style=\"color:#d496d4; background:none;\"} Reference\n\n\\- [ggplot for categorical-data](https://mq-software-carpentry.github.io/r-ggplot-extension/02-categorical-data/index.html){target=\"_blank\"}\\\n- [Describe function](https://www.geeksforgeeks.org/describe-function-in-r/){target=\"_blank\"}\\\n- [gt package](https://gt.rstudio.com/){target=\"_blank\"}\\\n- [theme for ggplot2](https://ggplot2.tidyverse.org/reference/theme.html){target=\"_blank\"}\\\n- [Recode Values with dplyr](https://dplyr.tidyverse.org/reference/recode.html){target=\"_blank\"}\\\n- [Customize tick marks and labels](https://www.sthda.com/english/wiki/ggplot2-axis-ticks-a-guide-to-customize-tick-marks-and-labels){target=\"_blank\"}\\\n- [National Statistical Standards Recommendations on Definition and Classification of Age](https://www.singstat.gov.sg/-/media/files/standards_and_classifications/nsa.ashx){target=\"_blank\"}\\\n- [Cencus of Population 2020](https://www.parliament.gov.sg/docs/default-source/default-document-library/cop2020sr2.pdf){target=\"_blank\"}\\\n- [Population Pyramid Plot](https://www.njtierney.com/post/2022/08/09/ggplot-pyramid/){target=\"_blank\"}\\\n- [Ageing Population](https://www.weforum.org/stories/2023/09/life-expectancy-countries-ageing-populations/){target=\"_blank\"}\\\n- [Heatmap ggplot2](https://r-charts.com/correlation/heat-map-ggplot2/){target=\"_blank\"}\\\n- [Chi Square in r](https://www.datacamp.com/tutorial/chi-square-test-r){target=\"_blank\"}\n\n# [7]{style=\"color:#d496d4; background:none;\"} Appendix\n\n## [7.1]{style=\"color:#d496d4; background:none;\"} Appendix A {#appendixa}\n\n| **Column Name** | **Description**             |\n|-----------------|-----------------------------|\n| PA              | Planning Area               |\n| SZ              | Subzone                     |\n| AG              | Age Group                   |\n| Sex             | Sex                         |\n| FA              | Floor Area of Residence     |\n| Pop             | Resident Count (Population) |\n| Time            | Time / Period               |\n\n: {tbl-colwidths=\"\\[20,80\\]\"}\n\n## [7.2]{style=\"color:#d496d4; background:none;\"} Appendix B {#appendixb}\n\n[National Statistical Standards Recommendations on Definition and Classification of Age](https://www.singstat.gov.sg/-/media/files/standards_and_classifications/nsa.ashx){target=\"_blank\"}\n\n| **AG**      | **AG_recode**   |\n|-------------|-----------------|\n| 0_to_4      | Below 20 years  |\n| 5_to_9      | Below 20 years  |\n| 10_to_14    | Below 20 years  |\n| 15_to_19    | Below 20 years  |\n| 20_to_24    | 20-64 Years     |\n| 25_to_29    | 20-64 Years     |\n| 30_to_34    | 20-64 Years     |\n| 35_to_39    | 20-64 Years     |\n| 40_to_44    | 20-64 Years     |\n| 45_to_49    | 20-64 Years     |\n| 50_to_54    | 20-64 Years     |\n| 55_to_59    | 20-64 Years     |\n| 60_to_64    | 20-64 Years     |\n| 65_to_69    | 65 years & Over |\n| 70_to_74    | 65 years & Over |\n| 75_to_79    | 65 years & Over |\n| 80_to_84    | 65 years & Over |\n| 85_to_89    | 65 years & Over |\n| 90_and_over | 65 years & Over |\n",
    "supporting": [
      "Take-home_Ex01-docx_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}